# Generated by Django 4.0.3 on 2022-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothinfo',
            name='GiraLength',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clothinfo',
            name='GozLength',
            field=models.FloatField(null=True),
        ),
    ]
