# Generated by Django 4.0.3 on 2022-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clothinfo_giralength_alter_clothinfo_gozlength'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('তারিখ', models.DateTimeField()),
                ('পোশাক', models.TextField()),
                ('টাকা', models.FloatField()),
                ('ধরন', models.CharField(choices=[('ডেবিট', 'devit'), ('ক্রেডিট', 'credit')], max_length=40)),
            ],
        ),
    ]
