# Generated by Django 4.0.3 on 2022-04-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopEvents',
            new_name='ShopEvent',
        ),
    ]
