# Generated by Django 4.0.3 on 2022-04-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_shopevents_shopevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopevent',
            name='ধরন',
            field=models.CharField(choices=[('devit', 'ডেবিট'), ('credit', 'ক্রেডিট')], max_length=40),
        ),
        migrations.AlterField(
            model_name='shopevent',
            name='পোশাক',
            field=models.CharField(max_length=500),
        ),
    ]
