# Generated by Django 4.0.3 on 2022-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shopevent_ধরন_alter_shopevent_পোশাক'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopevent',
            name='পরিমান',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopevent',
            name='রেট',
            field=models.FloatField(null=True),
        ),
    ]
