# Generated by Django 4.0.3 on 2022-04-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shopevent_পরিমান_shopevent_রেট'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopevent',
            name='তারিখ',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
