# Generated by Django 4.0.4 on 2022-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shopevent_তারিখ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopevent',
            name='তারিখ',
            field=models.DateField(),
        ),
    ]
