# Generated by Django 4.0.4 on 2022-04-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_shopevent_তারিখ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopevent',
            name='ধরন',
        ),
    ]
